### PR TITLE
Add middleman-basis

### PR DESCRIPTION
**Pull request by pzi**
Hi, 

This PR adds my template [middleman-basis](https://github.com/pzi/middleman-basis) to the template section.

Thanks & cheers
Patrik

### CODE REVIEW

**Comment by tdreyno** [comment]
Mind splitting this into 2 PRs? The Bourbon change needs to be tested visually, whereas the extension one can be merged immediately.

**Comment by pzi** [comment]
Sure @tdreyno, that's done :)

**Comment by pzi** [comment]
I heavily suspect the build is broken because Sass fails to compile due to the issue stated in #115 and bourbon needing and update :(

**Comment by pzi** [comment]
@tdreyno do you know when there will be a deploy of the site?
It's not listed on https://directory.middlemanapp.com/#/templates/all

**Comment by tdreyno** [comment]
Deploys are automatic, but it looks like something broke the build. Looking in to it.

**Pull request merged**
